@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

###
# LIST GAMES
GET {{host}}/games HTTP/1.1

###
# LIST ADS BY GAME
GET {{host}}/games/12/ads HTTP/1.1

###
# LIST ADS 
POST {{host}}/ads HTTP/1.1

###
# LIST DISCORD BY ADS
GET {{host}}/ads/11/discord HTTP/1.1

###
